config/routes.rb
RideCommunity::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers, :myRides, :join_rides, :my_messages
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :rides, only: [:new, :edit, :update, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :hitchhikes, only: [:create, :destroy]
  resources :messages, only: [:update, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_non_user_home.html.erb
<div class="center hero-unit">
  <h1>Welcome to Ride Community</h1>

  <h2>
    This is the home page for the Ride Community
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, 
                              class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/_user_home.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
    <section>
      <%= link_to "Add Ride", new_ride_path, 
                              class: "btn btn-large btn-primary" %>
    </section>
  </aside>
  <div class="span8">
    <h3>Rides Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <%= render 'static_pages/user_home' %>  
<% else %>
  <%= render 'static_pages/non_user_home' %>
<% end %> 