config/routes.rb
RideCommunity::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers, :myRides, :join_rides, :my_messages
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :rides, only: [:new, :edit, :update, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :hitchhikes, only: [:create, :destroy]
  resources :messages, only: [:update, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="rides">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= wrap(feed_item.user_address) %> to <%= wrap(feed_item.addressto) %> at <%= wrap(feed_item.scheduledfor.strftime("%d/%m/%Y %H:%M")) %> (<%= feed_item.calculate_distance %> km) </span>
  <span class="comment">
  	<%= wrap(feed_item.comment) %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <%= render 'rides/join_ride_form', ride: feed_item if signed_in? %>
  
</li>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= myRides_user_path(@user) %>">
    <strong id="ownRides" class="stat">
      <%= @user.rides.count %>
    </strong>
    Own Rides
  </a>
  <a href="<%= join_rides_user_path(@user) %>">
    <strong id="joinRides" class="stat">
      <%= @user.hitchhikes.count %>
    </strong>
    Join Rides
  </a>
  <a href="<%= my_messages_user_path(@user) %>">
    <strong id="messages" class="stat">
      <%= @user.messages.where(:seen => false).count %>
    </strong>
    New Messages
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
  <%= current_user.gender %>
  <%= current_user.age %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>