config/routes.rb
RideCommunity::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers, :myRides, :join_rides, :my_messages
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :rides, only: [:new, :edit, :update, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :hitchhikes, only: [:create, :destroy]
  resources :messages, only: [:update, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

end

app/models/ride.rb
class Ride < ActiveRecord::Base
	belongs_to :user
	validates :comment, length: { maximum: 140 }
	validates :user_id, presence: true
	validates :addressto, presence: true
	validates_datetime :scheduledfor, :after => lambda { DateTime.current }
	geocoded_by :ip_address
	geocoded_by :addressto
	after_validation :geocode_both
	has_many :hitchhikes, dependent: :destroy

	def user_address
		Geocoder.address([self.latitude, self.longitude])
	end

	def calculate_distance
		'%.2f' % Geocoder::Calculations.distance_between([self.latitude, self.longitude], [self.destlatitude, self.destlongitude], {:units => :km})
	end

	def join_ride?(user)
		hitchhikes.find_by(user_id: user.id)
	end

	def eligible_to_join?
		num_of_hitchhikes = hitchhikes.count
		
		!((num_of_hitchhikes == 4) || (user.vehicle_type == "Motorcycle" && num_of_hitchhikes == 1) || 
		  (user.age <= 21 && num_of_hitchhikes == 2) || (user.gender == "Female" && num_of_hitchhikes == 3))
	end

	def join_ride!(user)
		hitchhikes.create!(user_id: user.id)
	end

	def unjoin_ride!(user)
		hitchhikes.find_by(user_id: user.id).destroy!
	end

	def self.by_distance_and_date(user)
		future_rides = where("scheduledfor > :current_date and user_id <> :user_id", current_date: DateTime.now, user_id: user.id)

		distance = 1
		geoResultByUserIP = Geocoder.search(ip_address)
		center_point = [geoResultByUserIP[0].latitude, geoResultByUserIP[0].longitude]
		box = Geocoder::Calculations.bounding_box(center_point, distance, {:latitude => "latitude", :longitude => "longitude", :units => :km})
		future_rides.within_bounding_box(box)
		#Ride.near(center_point, distance, {:latitude => "latitude", :longitude => "longitude", :units => :km})
	end

	def self.ip_address
		if Rails.env.development?
			"81.218.191.82" #ramla hardcoded ip
			#"89.139.176.156" #home hardcoded ip
			#"89.139.176.156" #um kultum tel aviv hard coded ip
		else
			request.remote_ip
		end
	end

	private

		def ip_address
			if Rails.env.development?
				"81.218.191.82" #ramla hardcoded ip
				#"89.139.176.156" #home hardcoded ip
				#"89.139.176.156" #um kultum tel aviv hard coded ip
			else
				request.remote_ip
			end
		end

		def geocode_both
			geoResultForAddress = Geocoder.search(self.addressto)
			if geoResultForAddress.blank? || geoResultForAddress[0].blank?
				errors.add(:base, "Destination address is not valid.")
			else
				self.destlatitude = geoResultForAddress[0].latitude
				self.destlongitude = geoResultForAddress[0].longitude
			end

			geoResultForIP = Geocoder.search(ip_address)
			if geoResultForIP.blank? || geoResultForIP[0].blank?
				errors.add(:base, "IP address is not valid.")
			else
				self.latitude = geoResultForIP[0].latitude
				self.longitude = geoResultForIP[0].longitude
			end
		end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def new
    @ride = Ride.new
  end

  def create
    @ride = current_user.rides.build(ride_params)
    if @ride.save
      flash[:success] = "Ride created!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    @ride.destroy
    flash[:success] = "Ride deleted."
    redirect_to root_url
  end

  def edit
    @ride = Ride.find(params[:id])
  end

  def update
    @ride = Ride.find(params[:id])
    if @ride.update_attributes(ride_params)
      flash[:success] = "Ride updated"
      redirect_to myRides_user_path(@ride.user)
    else
      render 'edit'
    end
  end

  private

    def ride_params
      params.require(:ride).permit(:comment, :addressto, :scheduledfor)
    end

    def correct_user
      @ride = current_user.rides.find_by(id: params[:id])
      redirect_to root_url if @ride.nil?
    end
end

app/helpers/rides_helper.rb
module RidesHelper

  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : 
                                  text.scan(regex).join(zero_width_space)
    end
end

app/views/rides/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :addressto %>
<%= f.text_field :addressto %>

<%= f.label :scheduledfor %>
<span class="datetime"> <%= f.datetime_select :scheduledfor, :order => [:day, :month, :year], use_month_numbers: true %></span>

<%= f.label :comment %>
<%= f.text_field :comment %>

app/views/rides/_join_ride.html.erb
<% ride ||= @ride %>
<%= form_for(ride.hitchhikes.build(user_id: current_user.id, ride_id: ride.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :user_id %></div>
  <div><%= f.hidden_field :ride_id %></div>
  <%= f.submit "join", class: "link" %>
<% end %>

app/views/rides/_join_ride_form.html.erb
<% unless current_user?(ride.user) %>
	<div id="join_ride_form<%= ride.id %>"/>
		<% unless ride.eligible_to_join? %>
			ride is full
		<% else %>
			<% if ride.join_ride?(@user) %>
				<%= render 'rides/unjoin_ride', ride: ride %>
			<% else %>
				<%= render 'rides/join_ride', ride: ride %>
			<% end %>
		<% end %>
	</div>
<% end %>

app/views/rides/_ride.html.erb
<li>
  <%= link_to ride.user.name, ride.user %>
  
  <span class="content"><%= wrap(ride.user_address) %> to <%= wrap(ride.addressto) %> at <%= wrap(ride.scheduledfor.strftime("%d/%m/%Y %H:%M")) %> (<%= ride.calculate_distance %> km) </span>
  <span class="comment">
  	<%= wrap(ride.comment) %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(ride.created_at) %> ago.
  </span>
  <% if current_user?(ride.user) %>
  	| <%= link_to "edit", edit_ride_path(ride) %> | <%= link_to "delete", ride, method: :delete,
                              data: { confirm: "You sure?" } %>
  <% else %>
  	<%= render 'rides/join_ride_form', ride: ride if signed_in? %>
  <% end %>
  
</li>

app/views/rides/_unjoin_ride.html.erb
<% ride ||= @ride %>
<%= form_for(ride.hitchhikes.find_by(user_id: @user),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "unjoin", class: "link" %>
<% end %>

app/views/rides/create.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/rides/edit.html.erb
<% provide(:title, "Edit Ride") %> 
<h1>Update your ride</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@ride) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/rides/new.html.erb
<% provide(:title, 'Add Ride') %>
<h1>Add Ride</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@ride) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create a Ride", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>